### PR TITLE
Issue 32: error handling

### PR DESCRIPTION
**Pull request by stephanpelikan**
see https://github.com/camunda/camunda-bpm-camel/issues/32

### CODE REVIEW

**Comment by berndruecker** [comment]
Wouldn't it be preferrable that some exception is thrown instead of raising a BpmError? If the BpmnError is NOT catched, than the process instance is terminated - which is typically not the best way to handle the situation. If some Java exception is not catched, it is normally handled. And you can catch Java Exception classes within Bpmn Error Boundary Events.

**Comment by stephanpelikan** [comment]
> And you can catch Java Exception classes within Bpmn Error Boundary Events.

Oh, I didn't knew that. In https://docs.camunda.org/manual/7.7/examples/tutorials/error-handling/ this is not mentioned - or I can't find it. Which error has to be configured in BPMN? Or just leave the error boundary definition blank? Can you give me a hint? I would try it because it whould solve the problem without changing the code.

**Comment by berndruecker** [comment]
See https://docs.camunda.org/manual/7.7/reference/bpmn20/events/error-events/#defining-an-error - you can simply define a FQN of a Java class as error code. Feel free to also post a pull request in order to improve the tutorial you mention to include a hint :-) That would be totally awesome!

**Comment by stephanpelikan** [comment]
Using exception class names in BPMN processes is not that kind of abstraction for which BPMN is made for but the purpose blesses the tools ;-)

**Pull request closed without merging**
